Repository ansible/pytest-ansible, pull requests merged in 2023-12, with the labels that each got.

#220 Avoid use of deprecated pkg_resources
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  src/pytest_ansible/has_version.py
  src/pytest_ansible/molecule.py
  tests/test_adhoc.py
Labels: bug

#219 Optimize dependency updates
  .github/dependabot.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#222 Make requirements files compatible with dependabot
  .config/docs-requirements.txt
  .config/lock-requirements.txt
  .config/test-requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#223 More dependabot changes
  .config/constraints.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  tox.ini
Labels: skip-changelog

#224 Update dependabot update strategy
  .github/dependabot.yml
Labels: skip-changelog

#228 Switch default python from 3.9 to 3.10
  .config/constraints.txt
  .config/lock-requirements.txt
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog

#231 Require python 3.10 or newer
  .github/workflows/tox.yml
  README.md
  docs/getting_started.md
  pyproject.toml
  src/pytest_ansible/module_dispatcher/v2.py
  src/pytest_ansible/module_dispatcher/v212.py
  src/pytest_ansible/module_dispatcher/v213.py
  tox.ini
Labels: enhancement

#180 Fix duplicated host bug with extra_inventory
  .gitignore
  src/pytest_ansible/host_manager/__init__.py
  src/pytest_ansible/host_manager/v2.py
  src/pytest_ansible/host_manager/v212.py
  src/pytest_ansible/host_manager/v213.py
  src/pytest_ansible/module_dispatcher/__init__.py
  src/pytest_ansible/module_dispatcher/v2.py
  src/pytest_ansible/module_dispatcher/v212.py
  src/pytest_ansible/module_dispatcher/v213.py
  tests/conftest.py
  tests/test_adhoc_result.py
  tests/test_host_manager.py
  tests/test_module_dispatcher.py
Labels: bug
