Repository ansible/pytest-ansible, pull requests merged in 2023-10, with the labels that each got.

#184 ansible<8.0.0 in the setup.py
  setup.py
Labels: bug

#183 Extend pre-commit config
  .config/dictionary.txt
  .config/requirements-test.txt
  .gitignore
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog

#186 Remove Flake8 and revisit initial config for Ruff
  .flake8
  .pre-commit-config.yaml
  pyproject.toml
  src/pytest_ansible/has_version.py
  src/pytest_ansible/host_manager/__init__.py
  src/pytest_ansible/host_manager/v24.py
  src/pytest_ansible/module_dispatcher/__init__.py
  src/pytest_ansible/module_dispatcher/v1.py
  src/pytest_ansible/module_dispatcher/v2.py
  src/pytest_ansible/module_dispatcher/v212.py
  src/pytest_ansible/module_dispatcher/v213.py
  src/pytest_ansible/module_dispatcher/v24.py
  src/pytest_ansible/module_dispatcher/v28.py
  src/pytest_ansible/module_dispatcher/v29.py
  src/pytest_ansible/molecule.py
  src/pytest_ansible/plugin.py
  src/pytest_ansible/results.py
  src/pytest_ansible/units.py
  tests/conftest.py
  tests/integration/__init__.py
  tests/integration/test_molecule.py
  tests/test_adhoc.py
  tests/test_adhoc_result.py
  tests/test_host_manager.py
  tests/test_module_dispatcher.py
  tests/test_module_result.py
  tests/test_params.py
  tests/test_plugin.py
  tests/unit/test_unit.py
Labels: bug

#185 Add Python 3.12 to test matrix
  .config/requirements.in
  .config/requirements.txt
  .github/workflows/tox.yml
Labels: bug

#179 Move coverage to `pyproject.toml`
  .config/requirements-lock.txt
  .config/requirements-test.txt
  .config/requirements.in
  .config/requirements.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  codecov.yml
  pyproject.toml
  tox.ini
Labels: bug

#188 Enable CSpell check
  .config/dictionary.txt
  .pre-commit-config.yaml
  README.md
  cspell.config.yaml
  src/pytest_ansible/module_dispatcher/v213.py
  src/pytest_ansible/molecule.py
  src/pytest_ansible/plugin.py
  src/pytest_ansible/units.py
  tests/integration/test_molecule.py
  tests/test_adhoc.py
  tests/test_params.py
Labels: bug

#190 Fix codecov configuration
  .github/workflows/tox.yml
  codecov.yml
  pyproject.toml
  tox.ini
Labels: bug

#195 Fix codecov upload
  .github/CODEOWNERS
  .github/workflows/tox.yml
  codecov.yml
Labels: skip-changelog

#194 Additional hooks for pre-commit-hooks
  .config/dictionary.txt
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#192 Add Python 3.12 to project classifiers
  pyproject.toml
Labels: bug

#191 Setup prettier config
  .github/CODE_OF_CONDUCT.md
  .prettierignore
  .prettierrc.yaml
  HISTORY.md
  README.md
Labels: skip-changelog

#199 Initial mkdocs setup
  .config/requirements-docs.txt
  .config/requirements.txt
  .github/workflows/tox.yml
  .gitignore
  .readthedocs.yml
  cspell.config.yaml
  docs/index.md
  mkdocs.yml
  pyproject.toml
  tox.ini
Labels: bug

#204 Update pre-commit hooks
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#201 Require minimum python version to 3.9
  .github/workflows/tox.yml
  README.md
  pyproject.toml
  src/pytest_ansible/module_dispatcher/__init__.py
  tox.ini
Labels: enhancement

#207 Improve naming of tests
  tests/conftest.py
  tests/test_adhoc_result.py
  tests/test_host_manager.py
  tests/test_module_dispatcher.py
Labels: skip-changelog

#205 Cleanup test config
  .vscode/settings.json
  pyproject.toml
  tests/integration/test_molecule.py
  tox.ini
Labels: skip-changelog

#203 Change names of detected molecule tests to avoid name duplication
  .config/requirements-test.txt
  .config/requirements.txt
  src/pytest_ansible/molecule.py
  tests/integration/test_molecule.py
Labels: skip-changelog

#202 Avoid accidental plugin activation
  .config/dictionary.txt
  src/pytest_ansible/plugin.py
  tests/test_plugin.py
  tox.ini
Labels: bug

#210 Avoid early molecule importing
  pyproject.toml
  src/pytest_ansible/molecule.py
  src/pytest_ansible/plugin.py
  tests/integration/test_molecule.py
Labels: bug

#208 Remove dead-code related to unsupported ansible versions
  codecov.yml
  pyproject.toml
  src/pytest_ansible/has_version.py
  src/pytest_ansible/host_manager/__init__.py
  src/pytest_ansible/host_manager/v1.py
  src/pytest_ansible/host_manager/v24.py
  src/pytest_ansible/host_manager/v28.py
  src/pytest_ansible/host_manager/v29.py
  src/pytest_ansible/module_dispatcher/v1.py
  src/pytest_ansible/module_dispatcher/v24.py
  src/pytest_ansible/module_dispatcher/v28.py
  src/pytest_ansible/module_dispatcher/v29.py
  tests/conftest.py
  tests/test_adhoc_result.py
  tests/test_host_manager.py
  tests/test_module_dispatcher.py
  tests/test_params.py
Labels: bug
