Repository ansible/pytest-ansible, pull requests merged in 2023-09, with the labels that each got.

#172 Precommit update reqs
  .config/requirements.txt
Labels: bug

#164 Add tests for inventory
  .config/requirements.txt
  src/pytest_ansible/plugin.py
  tests/test_plugin.py
Labels: enhancement

#163 Add config option for `ANSIBLE_COLLECTIONS_PATH`
  src/pytest_ansible/units.py
Labels: enhancement

#178 fix project URLs
  .github/workflows/tox.yml
  pyproject.toml
Labels: skip-changelog

#175 Reduce linter rule exclusions (flake8/ pylint)
  pyproject.toml
  src/pytest_ansible/host_manager/__init__.py
  src/pytest_ansible/molecule.py
  src/pytest_ansible/plugin.py
  src/pytest_ansible/units.py
  tests/test_adhoc.py
  tests/unit/test_unit.py
Labels: skip-changelog
