Repository ansible/pytest-ansible, pull requests merged in 2023-03, with the labels that each got.

#72 Refactor packaging and CI/CD setup
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/main.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  setup.py
  src/pytest_ansible/__init__.py
  src/pytest_ansible/errors.py
  src/pytest_ansible/fixtures.py
  src/pytest_ansible/has_version.py
  src/pytest_ansible/host_manager/__init__.py
  src/pytest_ansible/host_manager/v1.py
  src/pytest_ansible/host_manager/v2.py
  src/pytest_ansible/host_manager/v212.py
  src/pytest_ansible/host_manager/v213.py
  src/pytest_ansible/host_manager/v24.py
  src/pytest_ansible/host_manager/v28.py
  src/pytest_ansible/host_manager/v29.py
  src/pytest_ansible/module_dispatcher/__init__.py
  src/pytest_ansible/module_dispatcher/v1.py
  src/pytest_ansible/module_dispatcher/v2.py
  src/pytest_ansible/module_dispatcher/v212.py
  src/pytest_ansible/module_dispatcher/v213.py
  src/pytest_ansible/module_dispatcher/v24.py
  src/pytest_ansible/module_dispatcher/v28.py
  src/pytest_ansible/module_dispatcher/v29.py
  src/pytest_ansible/plugin.py
  src/pytest_ansible/results.py
  tox.ini
Labels: enhancement

#77 Enable mypy
  .pre-commit-config.yaml
  pyproject.toml
  src/pytest_ansible/module_dispatcher/__init__.py
  src/pytest_ansible/module_dispatcher/v2.py
  src/pytest_ansible/module_dispatcher/v212.py
  tests/test_adhoc.py
  tests/test_fixtures.py
  tests/test_params.py
Labels: bug

#79 Remove outdated compatibility code
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  src/pytest_ansible/plugin.py
Labels: bug

#83 Enable `isort` via `pre-commit`
  .pre-commit-config.yaml
  pyproject.toml
  src/pytest_ansible/has_version.py
  src/pytest_ansible/host_manager/__init__.py
  src/pytest_ansible/host_manager/v1.py
  src/pytest_ansible/host_manager/v2.py
  src/pytest_ansible/host_manager/v212.py
  src/pytest_ansible/host_manager/v213.py
  src/pytest_ansible/host_manager/v24.py
  src/pytest_ansible/host_manager/v28.py
  src/pytest_ansible/host_manager/v29.py
  src/pytest_ansible/module_dispatcher/__init__.py
  src/pytest_ansible/module_dispatcher/v1.py
  src/pytest_ansible/module_dispatcher/v2.py
  src/pytest_ansible/module_dispatcher/v212.py
  src/pytest_ansible/module_dispatcher/v213.py
  src/pytest_ansible/module_dispatcher/v24.py
  src/pytest_ansible/module_dispatcher/v28.py
  src/pytest_ansible/module_dispatcher/v29.py
  src/pytest_ansible/plugin.py
  tests/conftest.py
  tests/test_adhoc.py
  tests/test_adhoc_result.py
  tests/test_fixtures.py
  tests/test_host_manager.py
  tests/test_module_dispatcher.py
  tests/test_module_result.py
  tests/test_params.py
Labels: bug

#82 Add vscode settings
  .vscode/settings.json
Labels: skip-changelog

#84 Support python 3.10 and 3.11
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .github/workflows/tox.yml
  pyproject.toml
  test-requirements.txt
  tox.ini
Labels: bug

#86 Enable prettier
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  HISTORY.md
  README.md
  pyproject.toml
Labels: bug
