Repository ansible/pytest-ansible, pull requests merged in 2023-08, with the labels that each got.

#141 Fix for ansible 2.9
  src/pytest_ansible/units.py
Labels: bug

#146 Update README.md
  README.md
Labels: skip-changelog

#156 Ignore new ruff errors
  pyproject.toml
Labels: bug

#155 Update requirements
  .config/requirements-lock.txt
  .config/requirements.txt
Labels: bug

#157 Avoid import error if molecule is not installed
  src/pytest_ansible/plugin.py
  tests/integration/test_molecule.py
Labels: bug

#159 Update docs to extend support for `units` & `molecule` functionality
  README.md
Labels: skip-changelog

#161 Update docs
  README.md
Labels: skip-changelog

#162 todo fixes & `__getattr__ ` method fix
  .config/requirements.txt
  src/pytest_ansible/host_manager/__init__.py
  src/pytest_ansible/module_dispatcher/__init__.py
  src/pytest_ansible/module_dispatcher/v2.py
  src/pytest_ansible/module_dispatcher/v212.py
  src/pytest_ansible/module_dispatcher/v213.py
  src/pytest_ansible/module_dispatcher/v24.py
  src/pytest_ansible/module_dispatcher/v28.py
  src/pytest_ansible/module_dispatcher/v29.py
  src/pytest_ansible/plugin.py
  src/pytest_ansible/units.py
  tests/test_adhoc.py
Labels: enhancement

#168 Rename driver delegated to default
  .gitignore
  tests/fixtures/molecule/default/molecule.yml
  tests/integration/test_molecule.py
Labels: skip-changelog

#169 fix: warning message
  tests/test_params.py
Labels: skip-changelog
