Repository ansible/pytest-ansible, pull requests merged in 2023-05, with the labels that each got.

#114 feature integrate `pytest-ansible-units`
  .config/dictionary.txt
  pyproject.toml
  src/pytest_ansible/plugin.py
  src/pytest_ansible/units.py
  tests/conftest.py
Labels: enhancement, feature

#116 Add some unit tests for units functionality
  .vscode/launch.json
  .vscode/settings.json
  tests/unit/__init__.py
  tests/unit/test_unit.py
Labels: skip-changelog

#117 Enable unit test support by default
  src/pytest_ansible/plugin.py
  tests/unit/test_unit.py
Labels: feature

#119 Add python 3.8 back
  .config/requirements.txt
  .github/workflows/tox.yml
  pyproject.toml
  src/pytest_ansible/module_dispatcher/__init__.py
  tests/unit/test_unit.py
Labels: bug

#120 Remove password
  .github/workflows/release.yml
Labels: skip-changelog

#127 Remove `ansible-core` as a runtime dep, move to testing
  .config/requirements-lock.txt
  .config/requirements-test.txt
  .config/requirements.in
  .config/requirements.txt
Labels: bug

#128 Restore python 3.7 support
  .config/requirements-lock.txt
  .config/requirements.txt
  .github/workflows/tox.yml
  pyproject.toml
Labels: bug
