Repository ansible/pytest-ansible, pull requests merged in 2025-06, with the labels that each got.

#467 Deprecate features no longer supported with ansible-core 2.19
  src/pytest_ansible/has_version.py
  src/pytest_ansible/host_manager/base.py
  src/pytest_ansible/plugin.py
  tests/conftest.py
  tests/test_adhoc.py
  tests/test_adhoc_result.py
  tests/test_fixtures.py
  tests/test_func.py
  tests/test_host_manager.py
  tests/test_module_dispatcher.py
  tests/test_params.py
  tests/test_plugin.py
Labels: minor

#474 Address some typing issues
  .config/pydoclint-baseline.txt
  pyproject.toml
  src/pytest_ansible/host_manager/base.py
  src/pytest_ansible/module_dispatcher/__init__.py
  src/pytest_ansible/module_dispatcher/v213.py
  src/pytest_ansible/molecule.py
  src/pytest_ansible/plugin.py
  src/pytest_ansible/results.py
  src/pytest_ansible/units.py
  tests/integration/test_molecule.py
  tests/test_adhoc_result.py
  tests/test_module_dispatcher.py
  tests/unit/test_unit.py
Labels: bug

#476 Enable few extra pytest plugins
  .config/constraints.txt
  .config/requirements.in
Labels: skip-changelog
